---
- name: Converge
  hosts: all
  become: true
  vars:
    horizon_host_name: "localhost"
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      changed_when: false
  roles:
    - role: b3n4kh.openstack-horizon
