---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "docker.io/pycontribs/ubuntu"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
